CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Fazendas" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Descricao" text NULL,
    CONSTRAINT "PK_Fazendas" PRIMARY KEY ("Id")
);

CREATE TABLE "Animais" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Identificador" text NULL,
    "FazendaId" bigint NOT NULL,
    CONSTRAINT "PK_Animais" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Animais_Fazendas_FazendaId" FOREIGN KEY ("FazendaId") REFERENCES "Fazendas" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Animais_FazendaId" ON "Animais" ("FazendaId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230123204810_initial', '6.0.13');

COMMIT;

